---
db:
  host: localhost
  port: 3306
  user: meetrics
  password: password
  database: meetrics
  rootUser: root
  rootPassword: password
  rootDatabase: mysql

google:
  subject: admin@gmail.com
  domain: yourdomain.com

rooms:
  - Green Conference Room
  - Zen Conference Room
  - Phone Room- Airstream (Interior) (2 seats)